### ISSUE TITLE
/ban doesn't check whether the targeted user is a member of the guild

### ISSUE THREAD

**Issue by TheKodeToad** [HyacinthBots/discord-moderation-actions#1]
### What happened?

- Someone said Lily wasn't working correctly
- On my own private testing server I banned him to see whether Lily was functioning properly
- It send a DM to him (I'm sorry :p)

I'd expect the bot to prevent sending a DM unless the user is in the server.

### Additional context

There are a few reasons why this isn't desirable:
- Confusion (I don't even know what this server is)
- Harassment (e.g. banned with reason "cheese!" 500 times in a row)

**Comment by NoComment1105** [comment]
Thanks for the report. I'm going to transfer this issue to the moderation actions repository, as we don't handle banning exactly inside Lily. 👍🏼

**Comment by NoComment1105** [comment]
Fixed in https://github.com/HyacinthBots/discord-moderation-actions/commit/91736f610af69f2110a477bfa50b633e8c1209aa
Pushed to release version v0.2.1
